<script lang="ts">
  import { navigate } from 'svelte-routing'
  import { ArrowLeft, Minus, Plus, ShoppingCart, Zap } from '@lucide/svelte'
  import { getCart, getProduct, saveCart } from '../data/store'
  let { id }: { id: string } = $props()
  let product = $state<Awaited<ReturnType<typeof getProduct>>>()
  let color = $state('')
  let quantity = $state(1)
  let added = $state(false)
  $effect(() => { getProduct(id).then((item) => { product = item; color = item?.colors[0] ?? '' }) })
  async function add(): Promise<void> { if (!product) return; const cart = await getCart(); const existing = cart.find((item) => item.productId === product?.id && item.color === color); if (existing) existing.quantity += quantity; else cart.push({ productId: product.id, quantity, color }); await saveCart(cart); added = true }
</script>

{#if product}<section class="mx-auto max-w-5xl"><button onclick={() => history.back()} class="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-muted hover:text-navy"><ArrowLeft size={17}/> Back to shop</button><div class="grid gap-8 rounded-panel bg-card p-5 shadow-sm ring-1 ring-line md:grid-cols-2 lg:p-8"><div class="grid min-h-80 place-items-center rounded-panel bg-surface text-9xl">{product.image}</div><div><p class="font-semibold text-primary">{product.category}</p><h1 class="mt-2 text-3xl font-bold text-navy">{product.name}</h1><p class="mt-3 text-accent">★ {product.rating} <span class="text-muted">({product.reviews} reviews)</span></p><div class="mt-5 flex items-baseline gap-3"><span class="text-3xl font-bold text-navy">${product.price}</span>{#if product.originalPrice}<span class="text-muted line-through">${product.originalPrice}</span>{/if}</div><p class="mt-6 leading-7 text-muted">{product.description}</p><p class={product.inStock ? 'mt-6 text-sm font-semibold text-success' : 'mt-6 text-sm font-semibold text-danger'}>{product.inStock ? 'In stock — ready to ship' : 'Currently out of stock'}</p><p class="mt-5 text-sm font-semibold text-navy">Color</p><div class="mt-2 flex gap-2">{#each product.colors as option}<button onclick={() => color = option} class={color === option ? 'rounded-lg border-2 border-primary px-3 py-2 text-sm font-semibold text-primary' : 'rounded-lg border border-line px-3 py-2 text-sm'}>{option}</button>{/each}</div><div class="mt-5 flex items-center gap-3"><span class="text-sm font-semibold text-navy">Quantity</span><div class="flex items-center rounded-lg border border-line"><button onclick={() => quantity = Math.max(1, quantity - 1)} class="p-2"><Minus size={16}/></button><span class="w-8 text-center font-semibold">{quantity}</span><button onclick={() => quantity += 1} class="p-2"><Plus size={16}/></button></div></div>{#if added}<p class="mt-4 rounded-lg bg-green-50 p-3 text-sm font-medium text-success">Added to your cart.</p>{/if}<div class="mt-6 flex flex-col gap-3 sm:flex-row"><button disabled={!product.inStock} onclick={add} class="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 font-semibold text-white disabled:opacity-50"><ShoppingCart size={18}/> Add to cart</button><button disabled={!product.inStock} onclick={async () => { await add(); navigate('/checkout') }} class="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-navy px-5 py-3 font-semibold text-white disabled:opacity-50"><Zap size={18}/> Buy now</button></div></div></div></section>{:else}<p class="p-8 text-muted">Loading product…</p>{/if}
